# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RcppCorels_rcpp_hello_world`)
}

#' R Interface to 'Certifiably Optimal RulE ListS (Corels)'
#'
#' Nothing here yet.
#' @title Corels interace
#' @return A constant bool for now
corels <- function() {
    .Call(`_RcppCorels_corels`)
}

