# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' R Interface to 'Certifiably Optimal RulE ListS (Corels)'
#'
#' Nothing here yet.
#' @title Corels interace
#' @param rules_file Character variable with rules file name
#' @param labels_file Character variable with labels file name
#' @param log_dir Character variable with logfile directory name
#' @param meta_file Optional character variable with labels file name
#' @param run_bfs Boolean toggle
#' @param calculate_size Boolean toggle
#' @param run_curiosity Boolean toggle
#' @param curiosity_policy Integer value
#' @param latex_out Boolean toggle
#' @param map_type Integer value
#' @param verbosity Integer value
#' @param max_num_nodes Integer value
#' @param regularization Double value
#' @param logging_frequency Integer value
#' @param ablation Double value
#' @return A constant bool for now
corels <- function(rules_file, labels_file, log_dir, meta_file = "", run_bfs = FALSE, calculate_size = FALSE, run_curiosity = FALSE, curiosity_policy = 0L, latex_out = FALSE, map_type = 0L, verbosity = 0L, max_num_nodes = 100000L, regularization = 0.01, logging_frequency = 1000L, ablation = 0L) {
    .Call(`_RcppCorels_corels`, rules_file, labels_file, log_dir, meta_file, run_bfs, calculate_size, run_curiosity, curiosity_policy, latex_out, map_type, verbosity, max_num_nodes, regularization, logging_frequency, ablation)
}

